version: "3.9"

services:
  # Дополняем базовый сервис БД (в базовом compose он называется "postgres")
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ssto -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - ssto-postgres   # алиас, чтобы хост ssto-postgres из env backend продолжал работать

  # Дополняем базовый сервис backend, НЕ меняя его окружение/переменные
  backend:
    depends_on:
      postgres:
        condition: service_healthy
