# docker-compose.override.yml
# Дополнительные сервисы для локальной разработки

version: '3.8'

services:
  # MailHog - для перехвата и просмотра email в разработке
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ssto-mailhog
    ports:
      - "1025:1025"  # SMTP сервер
      - "8025:8025"  # Web UI
    networks:
      - ssto-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Переопределяем backend для использования MailHog
  backend:
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_USER=
      - SMTP_PASS=
    depends_on:
      - postgres
      - mailhog

  # Добавляем pgAdmin для управления БД (опционально)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ssto-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ssto.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - ssto-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    profiles:
      - tools  # Запускается только с флагом --profile tools

networks:
  ssto-network:
    driver: bridge

volumes:
  pgadmin-data: