name: Functional Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend dependencies
        working-directory: backend-nest
        run: npm ci
      - name: Run backend unit tests
        run: npm run test:unit
        working-directory: backend-nest

  backend-contract:
    runs-on: ubuntu-latest
    needs: backend-unit
    env:
      SIMPLE_AUTH_MODE: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend dependencies
        working-directory: backend-nest
        run: npm ci
      - name: Run contract tests with pg-embed
        run: npm run test:contract
        working-directory: backend-nest

  smoke:
    runs-on: ubuntu-latest
    needs: backend-unit
    steps:
      - uses: actions/checkout@v4
      - name: Start services
        run: docker compose up -d backend frontend postgres mailhog
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl
      - name: Run smoke tests
        env:
          API_BASE: http://localhost:3001
          MAILHOG: http://localhost:8025
        run: |
          echo "Ensure backend is running in docker-compose before calling"
          bash tests/smoke.sh

  e2e:
    runs-on: ubuntu-latest
    needs: backend-contract
    steps:
      - uses: actions/checkout@v4
      - name: Start services
        run: docker compose up -d backend frontend postgres mailhog
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          API_BASE_URL: http://localhost:3001/api
          MAILHOG_URL: http://localhost:8025
          PLAYWRIGHT_BASE_URL: http://localhost:5173
        run: npm run test:e2e
